### ISSUE TITLE
Code is broken

### ISSUE THREAD

**Issue by mr-july** [hnakamur/api2go-gorm-gin-crud-example#5]
The example code is broken. I get the same error as Travis CI
```
http error (406) strconv.ParseInt: parsing "": invalid syntax and 0 more errors
```
So, user could not be created. :-(

Could you please repair it?

**Comment by hnakamur** [comment]
I'm sorry but this repository is not maintained since I had stopped using api2go and gin.
I'm afraid I have no time to repair it since I have other things to do.

Please fork this repository and fix it yourself.
Or if you are interested in maintaining this repository, I'm happy to transfer ownership to you.

**Comment by mr-july** [comment]
I've created a [Pull request](https://github.com/hnakamur/api2go-gorm-gin-crud-example/pull/6) could you please integrate it?

**Comment by hnakamur** [comment]
I've just merged it.
Thanks for your fix!
